version: 3

paths:
    exclude:
        - vendor/
        - plugins/
        - _tools/
        - includes/libraries/cryptojs/
        - includes/libraries/csrfp/
        - includes/libraries/ezimuel/
        - includes/libraries/plupload/
        - includes/libraries/yubico/
        - includes/language/
        - install/
